#!/usr/bin/env lua

-- Reimu - An autotools-like configure program that creates a nob build script

local cflags = "-Ofast -flto -pedantic"
local src = '"src/"'
local build = '"build/"'

--[[
--	Command line argument parsing
--]]
local function parseargs(args)
	local parsed = {}
	for i = 1, #args do
		local arg = args[i]
		local key, value = arg:match("^%-%-([^=]+)=(.+)$") -- I need to look up how this works KEKW
		if key and value then
			parsed[key] = value
		elseif arg:sub(1, 2) == "--" then
			parsed[arg:sub(3)] = true
		else
			table.insert(parsed, arg)
		end
	end
	return parsed
end

local flags = {
	compiler = "cc",
	cflags = "-Ofast -flto",
	downloader = "wget",
	help = "false",
	clean = "false",
	compile = "false",
	shell = "false",
	cross = "false",
}

local args = parseargs(arg)

for k, v in pairs(args) do
	if flags[k] ~= nil then
		flags[k] = v
	end
end

local function help()
	if flags.help == true then
		print("Reimu is a nob configurator in Lua.")
		print("")
		print("Flags:")
		-- The tabs are all aligned correctly. Don't worry.
		print(" --compiler=[COMMAND]	The command to use as the C compiler command. (default: cc)")
		print(' --cflags=[FLAGS]	The flags to use for the C compiler flags. (default: "-Ofast -flto"')
		print(" --downloader=[COMMAND]	The command to use as the downloader (default: wget)")
		print(" --compile		Automatically compiles and runs nob to compile after configuring.")
		print(" --cross		Uses specified compiler as if it was a cross compiler. Skips the testing. Does not work with --compile.")
		print(" --shell		Make a shell script equivelant to --compile. Deprecated in favor of --compile.")
		print(" --clean		Cleans out all the files generated. Useful for git commits.")
		print(" --help			Prints this help dialog.")
		os.exit(0)
	end
end

local function clean()
	if flags.clean == true then
		os.execute("rm -rfv nob build/ nob.c nob.h compile.sh src/ucvim")
		os.exit(0)
	end
end

local function cross()
	if flags.cross == true then
		cross = true
	else
		cross = false
	end
end

local function flagmain()
	help()
	clean()
	cross()
end

--[[
--	End Command line argument parsing
--]]

local function ifexists()
	print("Cleaning up before continuing...")

	local nobc = io.open("nob.c", "r")
	if nobc then
		os.remove("nob.c")
	end

	local nobh = io.open("nob.h", "r")
	if nobh then
		os.remove("nob.h")
	end

	local sh = io.open("compile.sh", "r")
	if sh then
		os.remove("compile.sh")
	end

	local test1c = io.open("test1.c", "r")
	if test1c then
		os.remove("test1.c")
	end

	local test1p = io.open("test1", "r")
	if test1p then
		os.remove("test1")
	end
end

local function includes()
	print("Adding basic includes to nob.c...")
	local nob = io.open("nob.c", "a+")
	io.output(nob)
	io.write("// Generated by Reimu by https://github.com/vmunix486\n")
	io.write("#define NOB_IMPLEMENTATION\n")
	io.write('#include "nob.h"\n')
	io.close(nob)
end

local function detect(cmd)
	local status = os.execute(cmd ..  " >/dev/null 2>&1")
	if status == true then 
		-- For whatever reason, the exit code does not follow the normal 0 or 1 scheme, it's either true or false
		return true
	else
		return false
	end
end

local function detectdownloader()
	local wgetstatus = detect("wget --version")
	-- If the user is using wget 1.x, then just a plain wget command will give a status code of 1, so use --version
	-- for both wget 1.x and wget2.
	if wgetstatus == true then
		print("wget does exist")
		downloader = "wget"
		return
	else
		print("wget does not exist")
	end

	local curlstatus = detect("curl --version")
	-- For some reason, just running "curl" gives an exit code of 2. --version gives 0.
	if curlstatus == true then
		print("curl does exist")
		downloader = "curl"
		return
	else
		print("curl does not exist")
	end

	print("") -- Red
	print("\27[31mYikes!\27[0m")
	print("\27[31mIt seems like you do not have either wget or curl!\27[0m")
	print("\27[31mYou can download them using your distribution's package manager,\27[0m")
	print("\27[31mor from compiling them from source:\27[0m")
	print("") -- Blue onwards
	print("\27[34mhttps://www.gnu.org/software/wget/\27[0m")
	print("\27[34mhttps://curl.se/\27[0m")
end

local function download()
	if downloader == "wget" then
		print("Downloading the latest nob.h from GitHub with wget...")
		-- July 16, 2026: updated command to use --no-check-certificate so it works on Windows XP
		os.execute("wget https://raw.githubusercontent.com/tsoding/nob.h/refs/heads/main/nob.h --no-check-certificate >/dev/null 2>&1")
		print("Finished downloading. Moving on.")
	end

	if downloader == "curl" then
		print("Downloading the latest nob.h from GitHub with curl...")
		os.execute("curl -O https://raw.githubusercontent.com/tsoding/nob.h/refs/heads/main/nob.h >/dev/null 2>&1")
		print("Finished downloading. Moving on.")
	end
end

local function detectcompiler()
	-- If flags.compiler is not cc, then set the specified compiler as the compiler
	if flags.compiler ~= "cc" then
		compiler = flags.compiler
		return
	end

	local ccstatus = detect("cc --version") -- This is --version for the same reason as curl
	if ccstatus == true then
		print("cc does exist.")
		compiler = "cc"
		return
	else
		print("cc does not exist.")
	end

	-- Oooooh fancy schmancy are we?
	print("")
	print("\27[31mYikes!\27[0m")
	print("\27[31mIt seems like you do not have a C compiler installed on your system.\27[0m")
	print("\27[31mIf you have one installed, but it is not set as being an option here, you should either modify the code\27[0m")
	print("\27[31mOr make an issue on the Github.\27[0m")
	print("")
	print("\27[31mIf you just do not have a C compiler... Womp Womp.\27[0m")
end

local function detectheaders(header)
	local file = io.open("/usr/include/" .. header, "r")
	if file then
		print(header .. " found.")
		io.close(file)
	else
		print(header .. " NOT found.")
		print(header .. " is needed for compilation.")
		-- io.close(file)
		os.exit(1)
	end
end

local function headers()
	detectheaders("assert.h")
	detectheaders("stdlib.h")
	detectheaders("stdio.h")
	detectheaders("errno.h")
	detectheaders("string.h")
	detectheaders("ctype.h")
	detectheaders("time.h")
	-- detectheaders("stdarg.h")
	detectheaders("locale.h")
	detectheaders("limits.h")
	detectheaders("termios.h")
	detectheaders("sys/types.h")
	detectheaders("sys/ioctl.h")
	detectheaders("sys/time.h")
	detectheaders("sys/wait.h")
	detectheaders("unistd.h")
	detectheaders("fcntl.h")
	detectheaders("signal.h")

	local wchar = io.open("/usr/include/wchar.h", "r")
	if wchar then
		print("wchar.h found.")
		wide = true
		io.close(wchar)
	else
		print("wchar.h NOT found.")
		print("It is not nessisary for compilation.")
		wide = false
		io.close(wchar)
	end

	local wctype = io.open("/usr/include/wctype.h", "r")
	if wctype then
		print("wctype.h found.")
		wide = true
		io.close(wctype)
	else
		print("wctype.h NOT found.")
		print("It is not nessisary for compilation.")
		wide = false
		io.close(wctype)
	end
end

local function testcompiler()
	print("Testing " .. compiler  .. "...")
	
	local test1 = io.open("test1.c", "a+")
	io.output(test1)
	io.write("/* Generated by Reimu by https://github.com/vmunix486 */\n")
	io.write("int main()\n")
	io.write("{\n")
	io.write("	return 0;\n")
	io.write("}\n")
	io.close(test1)

	local test1compilerstatus = os.execute(compiler .. " " .. cflags .. " " .. " test1.c -o test1 >/dev/null 2>&1")
	if test1compilerstatus == true then
		print("Compiler at least works...")
	else
		print("Compiler does not seem to work...")
		print("Maybe check the cflags?")
	end

	if cross == true then
		print("Skipping running the program...")
		print("You are putting a lot of trust into your cross compiler...")
		os.remove("test1")
		os.remove("test1.c")
	else
		local test1programstatus = os.execute("./test1")
		if test1programstatus == true then
			print("First test program works! Huzzah!")
			os.remove("test1")
			os.remove("test1.c")
		else
			print("The test program (which returns exit code 0) did not return 0.")
			print("I am at a loss of words as of how this is possible.")
			print("")
			print("FIX YOUR COMPILER!!!")
			os.remove("test1")
			os.remove("test1.c")
			os.exit(1)
		end
	end
end

-- tcflags = tokenize cflags
-- 1500 iq for naming
-- This is probably one of the most absolute bajoding parts of the project
local function tcflags()
	if flags.cflags ~= "-Ofast -flto" then
		cflags = flags.cflags
	end

	local out = {}

	for flag in string.gmatch(cflags, "%S+") do
		out[#out+1] = '"' .. flag .. '"'
	end

	tcflags = table.concat(out, ", ")end

local function finishnob()
	print("Finishing nob.c...")
        local nob = io.open("nob.c", "a+")
        io.output(nob)
        io.write("\n")
	io.write("#define BUILD_FOLDER " .. build .. "\n")
	io.write("#define SRC_FOLDER " .. src .. "\n")

	io.write("\n")

	io.write("int main(int argc, char **argv)\n")
	io.write("{\n")

	io.write("	NOB_GO_REBUILD_URSELF(argc, argv);\n")
	-- I know this isn't needed with Reimu, but I'm not sure if it's nessisary to have or not.
	io.write("	if (!nob_mkdir_if_not_exists(BUILD_FOLDER)) return 1;\n")
	io.write("	Nob_Cmd cmd = {0};\n")

	-- This is the special mojo sauce line
	-- Get all the sauce you need!
	if wide == true then
		io.write('	nob_cmd_append(&cmd, "' .. compiler .. '", "-D_WCHAR", ' .. tcflags .. ', "-o", BUILD_FOLDER"ucvim", SRC_FOLDER"ucvim.c");\n')
	else
		io.write('	nob_cmd_append(&cmd, "' .. compiler .. '", ' .. tcflags .. ', "-o", BUILD_FOLDER"ucvim", SRC_FOLDER"ucvim.c");\n')
	end
	io.write("	if (!nob_cmd_run(&cmd)) return 1;\n")
	io.write("	return 0;\n")

	io.write("}\n")

        io.close(nob)
end

local function shscript()
	if flags.shell == true then
		print("Creating compile.sh")
		local sh = io.open("compile.sh", "a+")
		io.output(sh)
		io.write("#!/bin/sh\n")
		io.write("\n# Generated by Reimu by vmunix. https://github.com/vmunix486\n")
		io.write(compiler .. " -o nob nob.c && ./nob\n")
		io.close(sh)
		os.execute("chmod +x ./compile.sh")
	end
end

local function compile()
	if flags.compile == true and flags.cross == true then
		print("")
		print("Sorry, but you have to compile nob.c with your system compiler manually.")
		print("When you set --compiler and --cross, it sets the same variable to everything for the compiler,")
		print("which is usually expected to make code for the same machine that you are compiling on,")
		print("and not cross compilation.")
		print("")
		print("Sorry for the inconveniance. You can figure it out on your own if you want.")
		print("Pull Requests are free and greatly appreciated.")
		return
	end
	if flags.compile == true then
		print("Compiling nob...")
		os.execute(compiler .. " " .. cflags .. " " .. " nob.c -o nob") -- WHY LUA WHY!?!??!?!?!?!?!?!
		print("Running nob...")
		os.execute("./nob")
	end
end

local function main()
	flagmain()
	ifexists()
	includes()
	detectdownloader()
	download()
	detectcompiler()
	headers()
	testcompiler()
	tcflags()
	finishnob()
	shscript()
	compile()
end

main()
